hi

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,62 +13,75 @@ jobs:
     - name: Checkout Repository
       uses: actions/checkout@v2
 
- - name: Trigger Jenkins and Capture Build Number
-  id: trigger_jenkins
-  run: |
-    # Trigger the job and get the queue item number
-    queue_item_url=$(curl -s -X POST "http://3.75.204.56:8080/job/ValidationPipeline/build?token=${{ secrets.JENKINS_TOKEN }}" \
-      -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} -H "${{ env.CRUMB }}" -D - \
-      | grep 'Location' | awk '{print $2}' | tr -d '\r')
+    - name: Fetch Jenkins Crumb
+      run: |
+        crumb=$(curl -s -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} "http://3.75.204.56:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)")
+        echo "Crumb received: $crumb"
+        echo "CRUMB=$crumb" >> $GITHUB_ENV
+      env:
+        JENKINS_USER: ${{ secrets.JENKINS_USER }}
+        JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
 
-    echo "Queue item URL: $queue_item_url"
-    
-    # Poll the queue item to get the actual build number
-    while true; do
-      response=$(curl -s -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} -H "${{ env.CRUMB }}" "${queue_item_url}api/json")
-      build_number=$(echo $response | jq -r '.executable.number')
-      
-      if [ "$build_number" != "null" ]; then
-        echo "Build number: $build_number"
-        echo "::set-output name=build_number::$build_number"
-        break
-      fi
-      sleep 5
-    done
-  env:
-    CRUMB: ${{ env.CRUMB }}
+    - name: Trigger Jenkins and Capture Build Number
+      id: trigger_jenkins
+      run: |
+        # Trigger the job and get the queue item number
+        queue_item_url=$(curl -s -X POST "http://3.75.204.56:8080/job/ValidationPipeline/build?token=${{ secrets.JENKINS_TOKEN }}" \
+          -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} -H "${CRUMB}" -D - \
+          | grep 'Location' | awk '{print $2}' | tr -d '\r')
 
-- name: Wait for Jenkins Job to Complete
-  run: |
-    build_number=${{ steps.trigger_jenkins.outputs.build_number }}
-    max_timeout=1800  # Maximum time to wait in seconds.
-    start_time=$(date +%s)
-    
-    while true; do
-      current_time=$(date +%s)
-      elapsed=$(( current_time - start_time ))
+        echo "Queue item URL: $queue_item_url"
+        
+        # Poll the queue item to get the actual build number
+        while true; do
+          response=$(curl -s -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} -H "${CRUMB}" "${queue_item_url}api/json")
+          build_number=$(echo $response | jq -r '.executable.number')
+          
+          if [ "$build_number" != "null" ]; then
+            echo "Build number: $build_number"
+            echo "::set-output name=build_number::$build_number"
+            break
+          fi
+          sleep 5
+        done
+      env:
+        JENKINS_USER: ${{ secrets.JENKINS_USER }}
+        JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
+        CRUMB: ${{ env.CRUMB }}
 
-      if [ $elapsed -ge $max_timeout ]; then
-        echo "Timed out waiting for Jenkins job to complete."
-        exit 1
-      fi
+    - name: Wait for Jenkins Job to Complete
+      run: |
+        build_number=${{ steps.trigger_jenkins.outputs.build_number }}
+        max_timeout=1800  # Maximum time to wait in seconds.
+        start_time=$(date +%s)
+        
+        while true; do
+          current_time=$(date +%s)
+          elapsed=$(( current_time - start_time ))
 
-      response=$(curl -s -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} -H "${{ env.CRUMB }}" "http://3.75.204.56:8080/job/ValidationPipeline/$build_number/api/json")
-      status=$(echo $response | jq -r '.result')
-      echo "Current job status: $status"
+          if [ $elapsed -ge $max_timeout ]; then
+            echo "Timed out waiting for Jenkins job to complete."
+            exit 1
+          fi
 
-      if [ "$status" == "SUCCESS" ]; then
-        echo "Jenkins job succeeded."
-        break
-      elif [ "$status" == "FAILURE" ]; then
-        echo "Jenkins job failed."
-        exit 1
-      fi
+          response=$(curl -s -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} -H "${CRUMB}" "http://3.75.204.56:8080/job/ValidationPipeline/$build_number/api/json")
+          status=$(echo $response | jq -r '.result')
+          echo "Current job status: $status"
 
-      sleep 30
-    done
-  env:
-    CRUMB: ${{ env.CRUMB }}
+          if [ "$status" == "SUCCESS" ]; then
+            echo "Jenkins job succeeded."
+            break
+          elif [ "$status" == "FAILURE" ]; then
+            echo "Jenkins job failed."
+            exit 1
+          fi
+
+          sleep 30
+        done
+      env:
+        JENKINS_USER: ${{ secrets.JENKINS_USER }}
+        JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
+        CRUMB: ${{ env.CRUMB }}
 
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
@@ -89,6 +102,6 @@ jobs:
 
     - name: Deploy to Machine 2
       run: |
-        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@18.199.67.122 "docker pull jadharfoush/chooseyourdress:latest && docker run -d --name chooseyourdress -p 8000:8000 jadharfoush/chooseyourdress:latest"
+        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@18.199.67.122 "docker pull jadharfoush/chooseyourdress:latest and docker run -d --name chooseyourdress -p 8000:8000 jadharfoush/chooseyourdress:latest"
       env:
         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
